<a href="https://colab.research.google.com/github/sarwar0001/Numpy/blob/main/eigen_pairs.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
A=np.array([[2,-2,3],[1,1,1],[1,3,-1]])
print(A)

[[ 2 -2  3]
 [ 1  1  1]
 [ 1  3 -1]]


In [3]:
#Calculate eign pairs
values,vectors=np.linalg.eig(A)
print(values)

[ 3.  1. -2.]


In [4]:
print(vectors)

[[ 0.57735027  0.57735027 -0.61684937]
 [ 0.57735027 -0.57735027 -0.05607722]
 [ 0.57735027 -0.57735027  0.78508102]]
