In [1]:
import numpy as np

In [6]:
P = np.array([[1,7],[2,1],[3,2]])
print(P)

[[1 7]
 [2 1]
 [3 2]]


In [3]:
Q = np.array([[1,1],[1,-1],[1,0]])
print(Q)

[[ 1  1]
 [ 1 -1]
 [ 1  0]]


In [8]:
C1 = np.add(P,Q)
print(C1)

[[2 8]
 [3 0]
 [4 2]]


In [9]:
C2 = np.subtract(P,Q)
print(C2)

[[0 6]
 [1 2]
 [2 2]]


In [10]:
R = np.array([[1,3,5],[1,2,1]])
print(R)

[[1 3 5]
 [1 2 1]]


In [11]:
C3 = np.dot(P,R)
print(C3)

[[ 8 17 12]
 [ 3  8 11]
 [ 5 13 17]]


In [12]:
C4 = np.linalg.det(C3)
print(C3)

[[ 8 17 12]
 [ 3  8 11]
 [ 5 13 17]]


In [13]:
S = np.array([[1,-1],[2,3]])
C5 = np.linalg.inv(S)
print(C5)

[[ 0.6  0.2]
 [-0.4  0.2]]
