In [ ]:
import numpy as np
v=np.array([1,-1,2])
w=np.array([2,5,2])

In [ ]:
print(v+w)

[3 4 4]


In [ ]:
print(v-w)

[-1 -6  0]


In [ ]:
print(3*v)

[ 3 -3  6]


In [ ]:
print(np.linalg.norm(v))

2.449489742783178


In [ ]:
s=np.dot(v,w)
print(s)

1
